Visualizer:
  Camera: 
      dist: 1.2
      position: [4.23, 5.21, 0.72]
      yaw: -89.5
      pitch: 307.4

Robot:
  base_init_pose: [3.6, 5.0, 0.0, 0.0, 0.0, 0.0]
  arm_urdf_path: "Asset/Robot/mobile_manipulator/arm/franka/urdf/panda.urdf"
  arm_num_dofs: 6
  arm_reset_jointValues: [0.282, -0.292, -0.583, -1.824, -0.161, 1.583]
  eef_id: 11