# Client parameters
Client:
  width: 2560                     # W
  height: 1440                    # H
  enable_Debug: False

# Visualizer params
Visualizer:
  Camera: 
      dist: 2.0
      position: [1.0, 0.0, 0]
      yaw: -86.4
      pitch: -52.3

# Robot params
Robot:
  arm_reset_jointValues: [0.98, 0.458, 0.31, -2.24, -0.30, 2.66, 2.32]                  # The initial angle of arm joint
  arm_urdf_path: "Asset/Robot/mobile_manipulator/arm/franka/urdf/panda.urdf"          # arm urdf
  arm_num_dofs: 7                                      # 7 DOF
  eef_id: 11